### ISSUE TITLE
Icons / אייקונים -- שאלה 🤷‍♀️

### ISSUE THREAD

**Issue by sandoku** [YohayHackam/HydrentControl#1]
היי (סנדי QA) האמת אני לא בטוחה ב-100% אם זה עדיין רלוונטי, אבל ביום ראשון רילי ביקשה ממני **לעדכן את כל האייקונים במערכת שאתה ויצחק עובדים עליה, כדי שבגרסה הסופית הצבעים שלהם יהיו תואמים לסוג ההתראה**..
הבנתי שזה יותר קשור לדברים של יצחק. ועדיפות לעשות את זה בצורה כזו שלא יפריע לעבודה שלכם, דרך ה GITHUB.

- אם כן, אני צריכה לפחות קישור ל**גרסה הכי אחרונה שיש** - להבין באיזה אייקונים מדובר ואיכן אלה מופיעים בדיוק.

**Comment by YohayHackam** [comment]
@sandoku 
זה ריפו של גרסה מאוד ישנה , הקוד החדש של הפורייקט מנוהל על-ידי עדי https://github.com/Adix1000

כרגע אנחנו בכלל לא מתעסקים בעיצוב ,רק בלוגיקה. 
יש כבר אייקונים שקיבלנו מנועה , באיזה שינויים מדובר ?

**Comment by sandoku** [comment]
@YohayHackam 

להבנתי הכוונה הייתה שאספק לכם את אותם האייקונים שאתם כבר משתמשים בהם/ בגרסתם הסופית, פשוט בצבעים שונים. כי כרגע הם בצבע אחד, אך אמורים לקבל צבע של ארוע עליו משויכים. 
### **אבל**
אם אייקון = בעצם פונקציה שמורה כ-SVG, אז שינוי הצבע זהה לשינוי צבע של טקסט. 
כלומר זה תחת התנאיות התצוגה, אשר בטח נמשכות אצלכם מ-CSS.
ואז (ברמת הלוגיקה נטו) משהו כמו:
IF (or for) event = waterFlow/trigger1 + status0
use "show-Style"/Cust.Properties = Orange(for icon)
וכו'
עכשיו.. גם אם היה לי כבר את ההסמכה לכתוב עניין כזה כטט-סקריפט ל React (ויכול אף להיות שהלוגיקה שציינתי מתאימה רק לפייתון) -- עדיין, 
it's a _beyond expectation_
שמישהו מבחוץ ייכנס ביומיים לדקויות של קוד שעבדתם עליו קרוב לחצי שנה..
נראה לי
/ או שלא הבנתי נכון
